"""add device pools and extend models

Revision ID: 5d3f1240a9d7
Revises: 
Create Date: 2026-04-02 13:56:03.918830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3f1240a9d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_pools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('reserved_ratio', sa.Float(), nullable=False),
    sa.Column('max_parallel', sa.Integer(), nullable=False),
    sa.Column('tag_selector', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_pools_name'), 'device_pools', ['name'], unique=True)
    op.create_table('fault_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('fault_stage', sa.String(length=32), nullable=False),
    sa.Column('fault_type', sa.String(length=64), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fault_profiles_fault_stage'), 'fault_profiles', ['fault_stage'], unique=False)
    op.create_index(op.f('ix_fault_profiles_fault_type'), 'fault_profiles', ['fault_type'], unique=False)
    op.create_index(op.f('ix_fault_profiles_name'), 'fault_profiles', ['name'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial', sa.String(length=64), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('system_version', sa.String(length=32), nullable=True),
    sa.Column('build_fingerprint', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('sync_failure_count', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('quarantine_reason', sa.Text(), nullable=True),
    sa.Column('current_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['device_pools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_pool_id'), 'devices', ['pool_id'], unique=False)
    op.create_index(op.f('ix_devices_serial'), 'devices', ['serial'], unique=True)
    op.create_index(op.f('ix_devices_status'), 'devices', ['status'], unique=False)
    op.create_table('upgrade_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('upgrade_type', sa.String(length=32), nullable=False),
    sa.Column('package_path', sa.String(length=512), nullable=True),
    sa.Column('source_build', sa.String(length=256), nullable=True),
    sa.Column('target_build', sa.String(length=256), nullable=True),
    sa.Column('fault_profile_id', sa.Integer(), nullable=True),
    sa.Column('validation_profile_id', sa.Integer(), nullable=True),
    sa.Column('default_pool_id', sa.Integer(), nullable=True),
    sa.Column('device_selector', sa.Text(), nullable=True),
    sa.Column('parallelism', sa.Integer(), nullable=False),
    sa.Column('enable_cycle_test', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['default_pool_id'], ['device_pools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fault_profile_id'], ['fault_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upgrade_plans_name'), 'upgrade_plans', ['name'], unique=False)
    op.create_table('run_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.Column('preemptible', sa.Boolean(), nullable=False),
    sa.Column('drill_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('failure_category', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('run_options', sa.Text(), nullable=True),
    sa.Column('current_iteration', sa.Integer(), nullable=False),
    sa.Column('total_iterations', sa.Integer(), nullable=False),
    sa.Column('parent_run_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['run_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['upgrade_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pool_id'], ['device_pools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_sessions_device_id'), 'run_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_run_sessions_plan_id'), 'run_sessions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_run_sessions_pool_id'), 'run_sessions', ['pool_id'], unique=False)
    op.create_index(op.f('ix_run_sessions_priority'), 'run_sessions', ['priority'], unique=False)
    op.create_index(op.f('ix_run_sessions_status'), 'run_sessions', ['status'], unique=False)
    op.create_table('device_leases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('leased_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('lease_status', sa.String(length=32), nullable=False),
    sa.Column('preemptible', sa.Boolean(), nullable=False),
    sa.Column('preempted_at', sa.DateTime(), nullable=True),
    sa.Column('preempted_by_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['run_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_leases_device_id'), 'device_leases', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_leases_run_id'), 'device_leases', ['run_id'], unique=False)
    op.create_table('run_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=32), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('stdout_path', sa.String(length=512), nullable=True),
    sa.Column('stderr_path', sa.String(length=512), nullable=True),
    sa.Column('step_result', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_steps_run_id'), 'run_steps', ['run_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('artifact_metadata', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['run_steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_run_id'), 'artifacts', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_run_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_run_steps_run_id'), table_name='run_steps')
    op.drop_table('run_steps')
    op.drop_index(op.f('ix_device_leases_run_id'), table_name='device_leases')
    op.drop_index(op.f('ix_device_leases_device_id'), table_name='device_leases')
    op.drop_table('device_leases')
    op.drop_index(op.f('ix_run_sessions_status'), table_name='run_sessions')
    op.drop_index(op.f('ix_run_sessions_priority'), table_name='run_sessions')
    op.drop_index(op.f('ix_run_sessions_pool_id'), table_name='run_sessions')
    op.drop_index(op.f('ix_run_sessions_plan_id'), table_name='run_sessions')
    op.drop_index(op.f('ix_run_sessions_device_id'), table_name='run_sessions')
    op.drop_table('run_sessions')
    op.drop_index(op.f('ix_upgrade_plans_name'), table_name='upgrade_plans')
    op.drop_table('upgrade_plans')
    op.drop_index(op.f('ix_devices_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_serial'), table_name='devices')
    op.drop_index(op.f('ix_devices_pool_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_fault_profiles_name'), table_name='fault_profiles')
    op.drop_index(op.f('ix_fault_profiles_fault_type'), table_name='fault_profiles')
    op.drop_index(op.f('ix_fault_profiles_fault_stage'), table_name='fault_profiles')
    op.drop_table('fault_profiles')
    op.drop_index(op.f('ix_device_pools_name'), table_name='device_pools')
    op.drop_table('device_pools')
    # ### end Alembic commands ###
